from __future__ import annotations

SHORT_HORIZON_CORE_PROFILE = "short_horizon_core_v1"
STYLE_STRUCTURAL_PROFILE = "style_structural_v1"
STYLE_STRUCTURAL_ALPHA_PROFILE = "style_structural_alpha_v2"
MEDIUM_HORIZON_PROFILE = "medium_horizon_v1"

DEFAULT_PROFILE = SHORT_HORIZON_CORE_PROFILE
PROFILE_NAMES = (
    SHORT_HORIZON_CORE_PROFILE,
    STYLE_STRUCTURAL_PROFILE,
    STYLE_STRUCTURAL_ALPHA_PROFILE,
    MEDIUM_HORIZON_PROFILE,
)
