"""Lightweight primitives for traditional quantitative research."""

from .backtest import BacktestResult, long_only_backtest
from .backtest_protocol import select_rebalance_dates, top_n_rebalance_backtest
from .dataset import load_daily_bars, load_daily_snapshot, load_daily_status, load_manifest, load_universe
from .dataset_v2 import (
    load_daily_universe,
    load_pit_daily_bars,
    load_pit_daily_size,
    load_pit_daily_status,
    load_pit_manifest,
    load_pit_snapshot,
    load_pit_stock_industry,
    load_quality_report,
    load_tradeable_panel,
)
from .data_audit import add_forward_return_labels, audit_bar_quality, audit_label_summary, audit_v2_data_labels
from .diagnostics import (
    assign_time_split,
    ic_by_date,
    quantile_returns,
    single_factor_diagnostics,
    summarize_factor_ic,
    top_n_backtest,
)
from .factors import annualized_volatility, momentum, moving_average, simple_returns, zscore
from .horizon_backtest import (
    HorizonBacktestResult,
    horizon_aligned_top_n_backtest,
    horizon_periods_per_year,
    period_horizon_summary,
    select_buffered_top_n,
    summarize_horizon_returns,
    yearly_horizon_summary,
)
from .metrics import annualized_return, max_drawdown, sharpe_ratio, volatility
from .multifactor import (
    add_equal_rank_score,
    add_ic_weighted_rank_score,
    add_prior_fit_pruned_rank_score,
    add_rank_score_from_weight_table,
    add_rolling_ic_weighted_rank_score,
    factor_coverage,
    mean_daily_factor_correlation,
    neutralize_factors_by_date,
    rolling_ic_weights_by_date,
    select_low_correlation_factors,
    weights_from_ic_summary,
)
from .portfolio import equal_weight, normalize_long_only, rank_long_short
from .research_panel import (
    DEFAULT_FACTOR_SET,
    FACTOR_SETS,
    add_baseline_score,
    add_cross_sectional_excess_return_labels,
    add_cross_sectional_zscores,
    build_factor_label_panel,
    default_factor_columns,
    expanded_factor_columns,
    factor_columns_for_set,
    load_baseline_factor_panel,
    normalize_factor_set,
    panel_summary,
)
from .size_source import (
    normalize_project_symbol,
    standardize_daily_size_frame,
    standardize_tushare_daily_basic_size,
    write_daily_size_parquet,
)
from .universe import (
    filter_sh_sz_a_shares,
    filter_sh_sz_mainboard_a_shares,
    is_active_common_stock_info,
    is_sh_sz_a_share,
    is_sh_sz_mainboard_a_share,
    is_st_name,
)

__all__ = [
    "BacktestResult",
    "DEFAULT_FACTOR_SET",
    "FACTOR_SETS",
    "HorizonBacktestResult",
    "add_baseline_score",
    "add_cross_sectional_zscores",
    "add_cross_sectional_excess_return_labels",
    "add_equal_rank_score",
    "add_forward_return_labels",
    "add_ic_weighted_rank_score",
    "add_prior_fit_pruned_rank_score",
    "add_rank_score_from_weight_table",
    "add_rolling_ic_weighted_rank_score",
    "annualized_return",
    "annualized_volatility",
    "assign_time_split",
    "audit_bar_quality",
    "audit_label_summary",
    "audit_v2_data_labels",
    "build_factor_label_panel",
    "default_factor_columns",
    "equal_weight",
    "expanded_factor_columns",
    "factor_coverage",
    "factor_columns_for_set",
    "filter_sh_sz_a_shares",
    "filter_sh_sz_mainboard_a_shares",
    "horizon_aligned_top_n_backtest",
    "horizon_periods_per_year",
    "ic_by_date",
    "is_active_common_stock_info",
    "is_sh_sz_a_share",
    "is_sh_sz_mainboard_a_share",
    "is_st_name",
    "load_daily_bars",
    "load_daily_universe",
    "load_daily_snapshot",
    "load_daily_status",
    "load_baseline_factor_panel",
    "load_manifest",
    "load_pit_daily_bars",
    "load_pit_daily_size",
    "load_pit_daily_status",
    "load_pit_manifest",
    "load_pit_snapshot",
    "load_pit_stock_industry",
    "load_quality_report",
    "load_tradeable_panel",
    "load_universe",
    "long_only_backtest",
    "max_drawdown",
    "mean_daily_factor_correlation",
    "neutralize_factors_by_date",
    "normalize_factor_set",
    "normalize_project_symbol",
    "momentum",
    "moving_average",
    "normalize_long_only",
    "panel_summary",
    "period_horizon_summary",
    "quantile_returns",
    "rank_long_short",
    "rolling_ic_weights_by_date",
    "select_low_correlation_factors",
    "select_buffered_top_n",
    "select_rebalance_dates",
    "sharpe_ratio",
    "simple_returns",
    "single_factor_diagnostics",
    "standardize_daily_size_frame",
    "standardize_tushare_daily_basic_size",
    "summarize_factor_ic",
    "summarize_horizon_returns",
    "top_n_backtest",
    "top_n_rebalance_backtest",
    "volatility",
    "weights_from_ic_summary",
    "write_daily_size_parquet",
    "yearly_horizon_summary",
    "zscore",
]
